language: go

go:
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - tip

before_install:
  - go get github.com/golang/lint/golint
  - go install github.com/golang/lint/golint

script:
 - go build
 - go vet
 - golint
 - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)